package serv1.db

object DBErrors {
  // Class 00 — Successful Completion
  object SUCCESSFUL {
    val SUCCESSFUL_COMPLETION = "00000"
  }

  // Class 01 — Warning
  object WARNING {
    val WARNING = "01000"
    val DYNAMIC_RESULT_SETS_RETURNED = "0100C"
    val IMPLICIT_ZERO_BIT_PADDING = "01008"
    val NULL_VALUE_ELIMINATED_IN_SET_FUNCTION = "01003"
    val PRIVILEGE_NOT_GRANTED = "01007"
    val PRIVILEGE_NOT_REVOKED = "01006"
    val STRING_DATA_RIGHT_TRUNCATION = "01004"
    val DEPRECATED_FEATURE = "01P01"
  }

  // Class 02 — No Data (this is also a warning class per the SQL standard)
  object NO_DATA {
    val NO_DATA = "02000"
    val NO_ADDITIONAL_DYNAMIC_RESULT_SETS_RETURNED = "02001"
  }

  // Class 03 — SQL Statement Not Yet Complete
  object NOT_YET_COMPLETE {
    val SQL_STATEMENT_NOT_YET_COMPLETE = "03000"
  }

  // Class 08 — Connection Exception
  object CONNECTION_EXCEPTION {
    val CONNECTION_EXCEPTION = "08000"
    val CONNECTION_DOES_NOT_EXIST = "08003"
    val CONNECTION_FAILURE = "08006"
    val SQLCLIENT_UNABLE_TO_ESTABLISH_SQLCONNECTION = "08001"
    val SQLSERVER_REJECTED_ESTABLISHMENT_OF_SQLCONNECTION = "08004"
    val TRANSACTION_RESOLUTION_UNKNOWN = "08007"
    val PROTOCOL_VIOLATION = "08P01"
  }

  // Class 09 — Triggered Action Exception
  val TRIGGERED_ACTION_EXCEPTION = "09000"
  // Class 0A — Feature Not Supported
  val FEATURE_NOT_SUPPORTED = "0A000"
  // Class 0B — Invalid Transaction Initiation
  val INVALID_TRANSACTION_INITIATION = "0B000"
  // Class 0F — Locator Exception
  val LOCATOR_EXCEPTION = "0F000"
  val INVALID_LOCATOR_SPECIFICATION = "0F001"
  // Class 0L — Invalid Grantor
  val INVALID_GRANTOR = "0L000"
  val INVALID_GRANT_OPERATION = "0LP01"
  // Class 0P — Invalid Role Specification
  val INVALID_ROLE_SPECIFICATION = "0P000"
  // Class 0Z — Diagnostics Exception
  val DIAGNOSTICS_EXCEPTION = "0Z000"
  val STACKED_DIAGNOSTICS_ACCESSED_WITHOUT_ACTIVE_HANDLER = "0Z002"
  // Class 20 — Case Not Found
  val CASE_NOT_FOUND = "20000"
  // Class 21 — Cardinality Violation
  val CARDINALITY_VIOLATION = "21000"

  // Class 22 — Data Exception
  object DATA_EXCEPTION {
    val DATA_EXCEPTION = "22000"
    val ARRAY_SUBSCRIPT_ERROR = "2202E"
    val CHARACTER_NOT_IN_REPERTOIRE = "22021"
    val DATETIME_FIELD_OVERFLOW = "22008"
    val DIVISION_BY_ZERO = "22012"
    val ERROR_IN_ASSIGNMENT = "22005"
    val ESCAPE_CHARACTER_CONFLICT = "2200B"
    val INDICATOR_OVERFLOW = "22022"
    val INTERVAL_FIELD_OVERFLOW = "22015"
    val INVALID_ARGUMENT_FOR_LOGARITHM = "2201E"
    val INVALID_ARGUMENT_FOR_NTILE_FUNCTION = "22014"
    val INVALID_ARGUMENT_FOR_NTH_VALUE_FUNCTION = "22016"
    val INVALID_ARGUMENT_FOR_POWER_FUNCTION = "2201F"
    val INVALID_ARGUMENT_FOR_WIDTH_BUCKET_FUNCTION = "2201G"
    val INVALID_CHARACTER_VALUE_FOR_CAST = "22018"
    val INVALID_DATETIME_FORMAT = "22007"
    val INVALID_ESCAPE_CHARACTER = "22019"
    val INVALID_ESCAPE_OCTET = "2200D"
    val INVALID_ESCAPE_SEQUENCE = "22025"
    val NONSTANDARD_USE_OF_ESCAPE_CHARACTER = "22P06"
    val INVALID_INDICATOR_PARAMETER_VALUE = "22010"
    val INVALID_PARAMETER_VALUE = "22023"
    val INVALID_PRECEDING_OR_FOLLOWING_SIZE = "22013"
    val INVALID_REGULAR_EXPRESSION = "2201B"
    val INVALID_ROW_COUNT_IN_LIMIT_CLAUSE = "2201W"
    val INVALID_ROW_COUNT_IN_RESULT_OFFSET_CLAUSE = "2201X"
    val INVALID_TABLESAMPLE_ARGUMENT = "2202H"
    val INVALID_TABLESAMPLE_REPEAT = "2202G"
    val INVALID_TIME_ZONE_DISPLACEMENT_VALUE = "22009"
    val INVALID_USE_OF_ESCAPE_CHARACTER = "2200C"
    val MOST_SPECIFIC_TYPE_MISMATCH = "2200G"
    val NULL_VALUE_NOT_ALLOWED = "22004"
    val NULL_VALUE_NO_INDICATOR_PARAMETER = "22002"
    val NUMERIC_VALUE_OUT_OF_RANGE = "22003"
    val SEQUENCE_GENERATOR_LIMIT_EXCEEDED = "2200H"
    val STRING_DATA_LENGTH_MISMATCH = "22026"
    val STRING_DATA_RIGHT_TRUNCATION = "22001"
    val SUBSTRING_ERROR = "22011"
    val TRIM_ERROR = "22027"
    val UNTERMINATED_C_STRING = "22024"
    val ZERO_LENGTH_CHARACTER_STRING = "2200F"
    val FLOATING_POINT_EXCEPTION = "22P01"
    val INVALID_TEXT_REPRESENTATION = "22P02"
    val INVALID_BINARY_REPRESENTATION = "22P03"
    val BAD_COPY_FILE_FORMAT = "22P04"
    val UNTRANSLATABLE_CHARACTER = "22P05"
    val NOT_AN_XML_DOCUMENT = "2200L"
    val INVALID_XML_DOCUMENT = "2200M"
    val INVALID_XML_CONTENT = "2200N"
    val INVALID_XML_COMMENT = "2200S"
    val INVALID_XML_PROCESSING_INSTRUCTION = "2200T"
    val DUPLICATE_JSON_OBJECT_KEY_VALUE = "22030"
    val INVALID_ARGUMENT_FOR_SQL_JSON_DATETIME_FUNCTION = "22031"
    val INVALID_JSON_TEXT = "22032"
    val INVALID_SQL_JSON_SUBSCRIPT = "22033"
    val MORE_THAN_ONE_SQL_JSON_ITEM = "22034"
    val NO_SQL_JSON_ITEM = "22035"
    val NON_NUMERIC_SQL_JSON_ITEM = "22036"
    val NON_UNIQUE_KEYS_IN_A_JSON_OBJECT = "22037"
    val SINGLETON_SQL_JSON_ITEM_REQUIRED = "22038"
    val SQL_JSON_ARRAY_NOT_FOUND = "22039"
    val SQL_JSON_MEMBER_NOT_FOUND = "2203A"
    val SQL_JSON_NUMBER_NOT_FOUND = "2203B"
    val SQL_JSON_OBJECT_NOT_FOUND = "2203C"
    val TOO_MANY_JSON_ARRAY_ELEMENTS = "2203D"
    val TOO_MANY_JSON_OBJECT_MEMBERS = "2203E"
    val SQL_JSON_SCALAR_REQUIRED = "2203F"
    val SQL_JSON_ITEM_CANNOT_BE_CAST_TO_TARGET_TYPE = "2203G"
  }

  // Class 23 — Integrity Constraint Violation
  val INTEGRITY_CONSTRAINT_VIOLATION = "23000"
  val RESTRICT_VIOLATION = "23001"
  val NOT_NULL_VIOLATION = "23502"
  val FOREIGN_KEY_VIOLATION = "23503"
  val UNIQUE_VIOLATION = "23505"
  val CHECK_VIOLATION = "23514"
  val EXCLUSION_VIOLATION = "23P01"
  // Class 24 — Invalid Cursor State
  val INVALID_CURSOR_STATE = "24000"
  // Class 25 — Invalid Transaction State
  val INVALID_TRANSACTION_STATE = "25000"
  val ACTIVE_SQL_TRANSACTION = "25001"
  val BRANCH_TRANSACTION_ALREADY_ACTIVE = "25002"
  val HELD_CURSOR_REQUIRES_SAME_ISOLATION_LEVEL = "25008"
  val INAPPROPRIATE_ACCESS_MODE_FOR_BRANCH_TRANSACTION = "25003"
  val INAPPROPRIATE_ISOLATION_LEVEL_FOR_BRANCH_TRANSACTION = "25004"
  val NO_ACTIVE_SQL_TRANSACTION_FOR_BRANCH_TRANSACTION = "25005"
  val READ_ONLY_SQL_TRANSACTION = "25006"
  val SCHEMA_AND_DATA_STATEMENT_MIXING_NOT_SUPPORTED = "25007"
  val NO_ACTIVE_SQL_TRANSACTION = "25P01"
  val IN_FAILED_SQL_TRANSACTION = "25P02"
  val IDLE_IN_TRANSACTION_SESSION_TIMEOUT = "25P03"
  // Class 26 — Invalid SQL Statement Name
  val INVALID_SQL_STATEMENT_NAME = "26000"
  // Class 27 — Triggered Data Change Violation
  val TRIGGERED_DATA_CHANGE_VIOLATION = "27000"
  // Class 28 — Invalid Authorization Specification
  val INVALID_AUTHORIZATION_SPECIFICATION = "28000"
  val INVALID_PASSWORD = "28P01"
  // Class 2B — Dependent Privilege Descriptors Still Exist
  val DEPENDENT_PRIVILEGE_DESCRIPTORS_STILL_EXIST = "2B000"
  val DEPENDENT_OBJECTS_STILL_EXIST = "2BP01"
  // Class 2D — Invalid Transaction Termination
  val INVALID_TRANSACTION_TERMINATION = "2D000"

  // Class 2F — SQL Routine Exception
  object SQL_ROUTINE_EXCEPTION {
    val SQL_ROUTINE_EXCEPTION = "2F000"
    val FUNCTION_EXECUTED_NO_RETURN_STATEMENT = "2F005"
    val MODIFYING_SQL_DATA_NOT_PERMITTED = "2F002"
    val PROHIBITED_SQL_STATEMENT_ATTEMPTED = "2F003"
    val READING_SQL_DATA_NOT_PERMITTED = "2F004"
  }

  // Class 34 — Invalid Cursor Name
  val INVALID_CURSOR_NAME = "34000"
  // Class 38 — External Routine Exception
  val EXTERNAL_ROUTINE_EXCEPTION = "38000"
  val CONTAINING_SQL_NOT_PERMITTED = "38001"
  val MODIFYING_SQL_DATA_NOT_PERMITTED = "38002"
  val PROHIBITED_SQL_STATEMENT_ATTEMPTED = "38003"
  val READING_SQL_DATA_NOT_PERMITTED = "38004"
  // Class 39 — External Routine Invocation Exception
  val EXTERNAL_ROUTINE_INVOCATION_EXCEPTION = "39000"
  val INVALID_SQLSTATE_RETURNED = "39001"
  val NULL_VALUE_NOT_ALLOWED = "39004"
  val TRIGGER_PROTOCOL_VIOLATED = "39P01"
  val SRF_PROTOCOL_VIOLATED = "39P02"
  val EVENT_TRIGGER_PROTOCOL_VIOLATED = "39P03"
  // Class 3B — Savepoint Exception
  val SAVEPOINT_EXCEPTION = "3B000"
  val INVALID_SAVEPOINT_SPECIFICATION = "3B001"
  // Class 3D — Invalid Catalog Name
  val INVALID_CATALOG_NAME = "3D000"
  // Class 3F — Invalid Schema Name
  val INVALID_SCHEMA_NAME = "3F000"
  // Class 40 — Transaction Rollback
  val TRANSACTION_ROLLBACK = "40000"
  val TRANSACTION_INTEGRITY_CONSTRAINT_VIOLATION = "40002"
  val SERIALIZATION_FAILURE = "40001"
  val STATEMENT_COMPLETION_UNKNOWN = "40003"
  val DEADLOCK_DETECTED = "40P01"
  // Class 42 — Syntax Error or Access Rule Violation
  val SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION = "42000"
  val SYNTAX_ERROR = "42601"
  val INSUFFICIENT_PRIVILEGE = "42501"
  val CANNOT_COERCE = "42846"
  val GROUPING_ERROR = "42803"
  val WINDOWING_ERROR = "42P20"
  val INVALID_RECURSION = "42P19"
  val INVALID_FOREIGN_KEY = "42830"
  val INVALID_NAME = "42602"
  val NAME_TOO_LONG = "42622"
  val RESERVED_NAME = "42939"
  val DATATYPE_MISMATCH = "42804"
  val INDETERMINATE_DATATYPE = "42P18"
  val COLLATION_MISMATCH = "42P21"
  val INDETERMINATE_COLLATION = "42P22"
  val WRONG_OBJECT_TYPE = "42809"
  val GENERATED_ALWAYS = "428C9"
  val UNDEFINED_COLUMN = "42703"
  val UNDEFINED_FUNCTION = "42883"
  val UNDEFINED_TABLE = "42P01"
  val UNDEFINED_PARAMETER = "42P02"
  val UNDEFINED_OBJECT = "42704"
  val DUPLICATE_COLUMN = "42701"
  val DUPLICATE_CURSOR = "42P03"
  val DUPLICATE_DATABASE = "42P04"
  val DUPLICATE_FUNCTION = "42723"
  val DUPLICATE_PREPARED_STATEMENT = "42P05"
  val DUPLICATE_SCHEMA = "42P06"
  val DUPLICATE_TABLE = "42P07"
  val DUPLICATE_ALIAS = "42712"
  val DUPLICATE_OBJECT = "42710"
  val AMBIGUOUS_COLUMN = "42702"
  val AMBIGUOUS_FUNCTION = "42725"
  val AMBIGUOUS_PARAMETER = "42P08"
  val AMBIGUOUS_ALIAS = "42P09"
  val INVALID_COLUMN_REFERENCE = "42P10"
  val INVALID_COLUMN_DEFINITION = "42611"
  val INVALID_CURSOR_DEFINITION = "42P11"
  val INVALID_DATABASE_DEFINITION = "42P12"
  val INVALID_FUNCTION_DEFINITION = "42P13"
  val INVALID_PREPARED_STATEMENT_DEFINITION = "42P14"
  val INVALID_SCHEMA_DEFINITION = "42P15"
  val INVALID_TABLE_DEFINITION = "42P16"
  val INVALID_OBJECT_DEFINITION = "42P17"
  // Class 44 — WITH CHECK OPTION Violation
  val WITH_CHECK_OPTION_VIOLATION = "44000"
  // Class 53 — Insufficient Resources
  val INSUFFICIENT_RESOURCES = "53000"
  val DISK_FULL = "53100"
  val OUT_OF_MEMORY = "53200"
  val TOO_MANY_CONNECTIONS = "53300"
  val CONFIGURATION_LIMIT_EXCEEDED = "53400"
  // Class 54 — Program Limit Exceeded
  val PROGRAM_LIMIT_EXCEEDED = "54000"
  val STATEMENT_TOO_COMPLEX = "54001"
  val TOO_MANY_COLUMNS = "54011"
  val TOO_MANY_ARGUMENTS = "54023"
  // Class 55 — Object Not In Prerequisite State
  val OBJECT_NOT_IN_PREREQUISITE_STATE = "55000"
  val OBJECT_IN_USE = "55006"
  val CANT_CHANGE_RUNTIME_PARAM = "55P02"
  val LOCK_NOT_AVAILABLE = "55P03"
  val UNSAFE_NEW_ENUM_VALUE_USAGE = "55P04"
  // Class 57 — Operator Intervention
  val OPERATOR_INTERVENTION = "57000"
  val QUERY_CANCELED = "57014"
  val ADMIN_SHUTDOWN = "57P01"
  val CRASH_SHUTDOWN = "57P02"
  val CANNOT_CONNECT_NOW = "57P03"
  val DATABASE_DROPPED = "57P04"
  val IDLE_SESSION_TIMEOUT = "57P05"
  // Class 58 — System Error (errors external to PostgreSQL itself)
  val SYSTEM_ERROR = "58000"
  val IO_ERROR = "58030"
  val UNDEFINED_FILE = "58P01"
  val DUPLICATE_FILE = "58P02"
  // Class 72 — Snapshot Failure
  val SNAPSHOT_TOO_OLD = "72000"
  // Class F0 — Configuration File Error
  val CONFIG_FILE_ERROR = "F0000"
  val LOCK_FILE_EXISTS = "F0001"
  // Class HV — Foreign Data Wrapper Error (SQL/MED)
  val FDW_ERROR = "HV000"
  val FDW_COLUMN_NAME_NOT_FOUND = "HV005"
  val FDW_DYNAMIC_PARAMETER_VALUE_NEEDED = "HV002"
  val FDW_FUNCTION_SEQUENCE_ERROR = "HV010"
  val FDW_INCONSISTENT_DESCRIPTOR_INFORMATION = "HV021"
  val FDW_INVALID_ATTRIBUTE_VALUE = "HV024"
  val FDW_INVALID_COLUMN_NAME = "HV007"
  val FDW_INVALID_COLUMN_NUMBER = "HV008"
  val FDW_INVALID_DATA_TYPE = "HV004"
  val FDW_INVALID_DATA_TYPE_DESCRIPTORS = "HV006"
  val FDW_INVALID_DESCRIPTOR_FIELD_IDENTIFIER = "HV091"
  val FDW_INVALID_HANDLE = "HV00B"
  val FDW_INVALID_OPTION_INDEX = "HV00C"
  val FDW_INVALID_OPTION_NAME = "HV00D"
  val FDW_INVALID_STRING_LENGTH_OR_BUFFER_LENGTH = "HV090"
  val FDW_INVALID_STRING_FORMAT = "HV00A"
  val FDW_INVALID_USE_OF_NULL_POINTER = "HV009"
  val FDW_TOO_MANY_HANDLES = "HV014"
  val FDW_OUT_OF_MEMORY = "HV001"
  val FDW_NO_SCHEMAS = "HV00P"
  val FDW_OPTION_NAME_NOT_FOUND = "HV00J"
  val FDW_REPLY_HANDLE = "HV00K"
  val FDW_SCHEMA_NOT_FOUND = "HV00Q"
  val FDW_TABLE_NOT_FOUND = "HV00R"
  val FDW_UNABLE_TO_CREATE_EXECUTION = "HV00L"
  val FDW_UNABLE_TO_CREATE_REPLY = "HV00M"
  val FDW_UNABLE_TO_ESTABLISH_CONNECTION = "HV00N"
  // Class P0 — PL/pgSQL Error
  val PLPGSQL_ERROR = "P0000"
  val RAISE_EXCEPTION = "P0001"
  val NO_DATA_FOUND = "P0002"
  val TOO_MANY_ROWS = "P0003"
  val ASSERT_FAILURE = "P0004"
  // Class XX — Internal Error
  val INTERNAL_ERROR = "XX000"
  val DATA_CORRUPTED = "XX001"
  val INDEX_CORRUPTED = "XX002"
}
