/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package serv1

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner
import serv1.app.App

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite {
  test("App has a greeting") {
    assert(App != null)
  }
}
