/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    flatDir {
        dirs("../libs")
    }
}

dependencies {
    val scalaVersion = "2.13"
    val akkaHttpVersion = "10.2.9"
    val akkaVersion = "2.6.8"
    val swaggerVersion = "2.2.1"

    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:2.13.3")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.0-jre")

    // Use Scalatest for testing our library
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.scalatest:scalatest_2.13:3.2.3")
    testImplementation("org.scalatestplus:junit-4-13_2.13:3.2.2.0")

    // Need scala-xml at test runtime
    testRuntimeOnly("org.scala-lang.modules:scala-xml_2.13:1.2.0")

    implementation("com.typesafe.akka:akka-http-bom_${scalaVersion}:10.2.9")

    implementation("com.typesafe.akka:akka-actor-typed_${scalaVersion}:${akkaVersion}")
    implementation("com.typesafe.akka:akka-stream_${scalaVersion}:${akkaVersion}")
    implementation("com.typesafe.akka:akka-stream-typed_${scalaVersion}:${akkaVersion}")
    implementation("com.typesafe.akka:akka-http_${scalaVersion}:${akkaHttpVersion}")
    implementation("com.typesafe.akka:akka-http-spray-json_${scalaVersion}:${akkaHttpVersion}")

    implementation("jakarta.ws.rs:jakarta.ws.rs-api:3.1.0")

    implementation("com.github.swagger-akka-http:swagger-akka-http_${scalaVersion}:2.4.2")

    implementation("com.typesafe.slick:slick_${scalaVersion}:3.4.0")
    implementation("com.typesafe.slick:slick-hikaricp_${scalaVersion}:3.4.0")
    implementation("com.typesafe.slick:slick-codegen_${scalaVersion}:3.4.0")
    implementation("org.postgresql:postgresql:42.5.1")
    implementation("org.slf4j:slf4j-nop:2.0.5")

    implementation("io.swagger.core.v3:swagger-core-jakarta:${swaggerVersion}")
    implementation("io.swagger.core.v3:swagger-annotations-jakarta:${swaggerVersion}")
    implementation("io.swagger.core.v3:swagger-models-jakarta:${swaggerVersion}")
    implementation("io.swagger.core.v3:swagger-jaxrs2-jakarta:${swaggerVersion}")

    implementation("", "TwsApi")
}

application {
    // Define the main class for the application.
    mainClass.set("serv1.App")
}
